### ISSUE TITLE
Write fixture with multiple names and emails.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#14]
We need a fixture that we can use to test sending email to multiple recipients in a single POST request.

**Comment by mitchellporter** [comment]
@nelsonic I'm interested in implementing this. Am I correct that a `fixture` is no different than a `stub`? Looks like they both mean the same thing.

Some quick questions.. would you want the creation of the fixture to be it's own PR, or can I create the fixture and add a test that sends an email to multiple recipients for a single PR? 

Also, would the related test go in `areal.test.js` or `sendemail.functional.test.js`? I'm assuming it would go in `areal.test.js` because there is a similar test in there but not really sure what the difference is between those two test files, since the names sound like they are meant to accomplish the same thing, unless I'm misunderstanding something?

**Comment by mitchellporter** [comment]
@nelsonic Did you get a chance to read my previous comment? I'm focusing more now on OSS and excited to get started on this + a bunch of other DWYL issues, but have some quick questions like the one above.. I want to make sure I get off to a good start so I can do a good job :)

I realize you're probably busy but wanted to bump this just in case you saw the notification previously and forgot about it.

Thanks!

**Comment by nelsonic** [comment]
Hi @mitchellporter! Yes, read it and then failed to reply! 🤦‍♂️ 
The way we intend to "_solve_" this issue is with an _elaborate_ "real" test which sends a _real_ email to domain we control, the email body will be saved to S3 via SES / Lambda Function
see: https://github.com/dwyl/learn-aws-lambda/pull/99
